name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-110-219-106.ap-south-1.compute.amazonaws.com 'bash -s' << 'EOF'
            cd /var/www/html/practice
            git pull origin main
            # Run your build and deployment commands here
            # For example, if you are using Node.js
            npm install
            npm install pm2
            npm run build
            pm2 restart all # If you are using PM2 to manage your node processes
          EOF