name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USER}}

        run: |
          '
            cd /var/www/html/practice &&
            git pull origin main &&
            npm install &&
            npm install pm2 &&
            npm run build &&
            pm2 restart all
          '