name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USER}}

        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ls -la private_key # List file details to ensure it exists and has the right permissions
          ssh -v -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /var/www/html/practice &&
            git pull origin main &&
            npm install &&
            npm install pm2 &&
            npm run build &&
            pm2 restart all
          '